controllers/AttributeClubController.php
<?php
namespace app\controllers;

use app\src\entities\attribute\Attribute;
use app\src\entities\attribute\AttributeClubSearch;
use app\src\library\BaseController;

class AttributeClubController extends BaseController
{
    public function actionGetCreateForm()
    {
        $attributeId = (int) $this->getParam('attributeId');
        $clubId = (int) $this->getParam('clubId');

        if (!$attributeId) {
            $attribute = new Attribute();
            $attribute->parent_id = $clubId;
        } else {
            $attribute = Attribute::findOne(['id' => $attributeId]);
        }

        $form = $this->renderAjax('/club/partial/attribute_form', [
            'attribute' => $attribute,
            'names' => Attribute::getAvailableAttributesNames(),
            'types' => Attribute::getTypeLabels(),
            'renderAjax' => true,
        ]);

        return $this->responseJson([
            'html' => $form,
        ]);
    }

    public function actionAddAttribute()
    {
        $attributes = $this->getParams();
        $clubId = (int) $this->getParam('clubId');

            $attribute = new Attribute();
            $attribute->load($attributes);
            Attribute::deleteAll([
                'id' => $attribute->id,
                'parent_id' => $clubId
            ]);
            $attribute->parent_id = $clubId;
            $attribute->save();

        $attributeSearch = new AttributeClubSearch($clubId);

        $attributesList = $this->renderAjax('/club/partial/attributes-list', [
            'attributesDataProvider' => $attributeSearch->getSearchDataProvider(),
        ]);

        return $this->responseJson([
            'html' => $attributesList,
        ]);
    }

    public function actionDelete()
    {
        $clubId = (int) $this->getParam('clubId');
        $attributeId = (int) $this->getParam('attributeId');

        Attribute::deleteAll([
            'id' => $attributeId,
            'parent_id' => $clubId
        ]);

        $attributesSearch = new AttributeClubSearch($clubId);

        $attributesList = $this->renderAjax('/club/partial/attributes-list', [
            'attributesDataProvider' => $attributesSearch->getSearchDataProvider(),
        ]);

        return $this->responseJson([
            'html' => $attributesList,
        ]);
    }
}

controllers/ClubController.php
<?php
namespace app\controllers;

use app\src\entities\AbstractModel;
use app\src\entities\attribute\AttributeClubSearch;
use app\src\entities\customer\CustomerPlaceSearch;
use app\src\entities\image\Image;
use app\src\entities\place\Club;
use app\src\entities\place\ClubSearch;
use app\src\entities\staff\StaffPositionPlaceSearch;
use app\src\entities\user\User;
use app\src\library\AccessChecker;
use app\src\library\BaseController;
use app\src\service\ClubService;
use app\src\service\ImageService;
use app\src\service\PlaceService;

/**
 * Class ClubController
 */
class ClubController extends BaseController
{
    /**
     * Lists all Club models.
     */
    public function actionIndex()
    {
        $place = new ClubSearch();
        $params = \Yii::$app->request->queryParams;
        $dataProvider = $place->getSearchDataProvider($params);

        $this->appendEntryPoint();

        return $this->render('index', [
            'searchModel' => $place,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate()
    {
        $attributes = $this->getParams();

        $clubService = new ClubService();
        $club = $clubService->createEmptyClub($attributes);

        $redirectUrl = '/club/update?id=' . $club->id;
        if (!AccessChecker::hasPermission('club.update')) {
            $redirectUrl = '/club/index';
        }

        return $this->responseJson([
            'redirectUrl' => $redirectUrl,
        ]);
    }

    public function actionGetCreateClubForm()
    {
        $form = $this->renderAjax('/club/partial/create-club-form', [
            'club' => new Club(),
        ]);

        return $this->responseJson([
            'html' => $form,
        ]);
    }

    public function actionDelete()
    {
        $clubId = $this->getParam('id');
        $isAjax = $this->getParam('isAjax');

        $clubService = new PlaceService();
        $clubService->deleteById($clubId);

        if ($isAjax) {
            return $this->responseListing(new ClubSearch(), '/club/index');
        }

        return $this->redirect('/club/index');
    }

    public function actionUpdate($id)
    {
        $owners = User::getOwnerList();
        $club = Club::findOne($id);
        $params = $this->getParams();

        $staffPositionPlaceSearch = new StaffPositionPlaceSearch($club->id);
        $customerPlaceSearch = new CustomerPlaceSearch($club->id);
        $attributePlaceSearch = new AttributeClubSearch($club->id);

        $this->appendEntryPoint();

        return $this->render('create', [
            'club' => $club,
            'owners' => $owners,
            'staffPositionPlaceSearch' => $staffPositionPlaceSearch,
            'staffDataProvider' => $staffPositionPlaceSearch->getSearchDataProvider($params),
            'clientsDataProvider' => $customerPlaceSearch->getSearchDataProvider(),
            'attributesDataProvider' => $attributePlaceSearch->getSearchDataProvider(),
        ]);
    }

    /**
     * @param $id
     * @throws \app\src\exception\ModelValidateException
     */
    public function actionUpdateInfo($id)
    {
        $attributes = \Yii::$app->request->post();

        $club = Club::findOne($id);
        $club->load($attributes);
        $club->updated_at = $club->updated_at ?? AbstractModel::getDateTimeNow();
        $club->updated_by = $club->updated_by ?? \Yii::$app->user->getId();
        $club->throwExceptionIfNotValid();
        $club->save();
        $this->appendEntryPoint('club.update');
    }

    public function actionUploadImages($id)
    {
        $club = Club::findOne($id);

        $imageService = new ImageService();
        $imageService->uploadImages($club, $_FILES, Image::TYPE_PLACE_PHOTO);
        $imageService->uploadLogo($club, $_FILES, Image::TYPE_PLACE_LOGO);
    }

    /**
     * @param $id
     * @param $filename
     * @param $extPath
     * @param AbstractModel $modelClass
     * @return array
     */
    public function actionDeleteImage($id, $filename, $extPath, AbstractModel $modelClass = null)
    {
        return parent::actionDeleteImage($id, $filename, $extPath, new Club());
    }
}

controllers/CustomerPlaceController.php
<?php
namespace app\controllers;

use app\src\entities\customer\Customer;
use app\src\entities\customer\CustomerPlace;
use app\src\entities\customer\CustomerPlaceSearch;
use app\src\exception\ModelValidateException;
use app\src\library\BaseController;
use app\src\service\CustomerPlaceService;
use app\src\service\UserService;

class CustomerPlaceController extends BaseController
{
    public function actionAddCustomersForm()
    {
        $clubId = (int) $this->getParam('clubId');

        $customerPlaceService = new CustomerPlaceService();
        $availableCustomers = $customerPlaceService->getAvailableNewCustomerIdsForClub($clubId);

        $customersForm = $this->renderAjax('/club/partial/customer-club-form', [
            'customerPlace' => new CustomerPlace(),
            'availableCustomers' => $availableCustomers,
        ]);

        return $this->responseJson([
            'html' => $customersForm,
        ]);
    }

    public function actionGetCreateForm()
    {
        $clubId = (int) $this->getParam('clubId');

        $customer = new Customer();
        $customerPlace = new CustomerPlace();
        $customerPlace->place_id = $clubId;

        $form = $this->renderAjax('/customer/partial/customer_form', [
            'customer' => $customer,
            'customerPlace' => $customerPlace,
            'renderAjax' => true,
        ]);

        return $this->responseJson([
            'html' => $form,
        ]);
    }

    public function actionGetUpdateForm()
    {
        $clubId = (int) $this->getParam('club_id');
        $customerId = (int) $this->getParam('customer_id');

        $customer = Customer::findOne(['id' => $customerId]);

        $customerPlace = CustomerPlace::findOne([
            'user_id' => $customerId,
            'place_id' => $clubId,
        ]);

        $form = $this->renderAjax('/customer/partial/customer_form', [
            'customer' => $customer,
            'customerPlace' => $customerPlace,
            'renderAjax' => true,
        ]);

        return $this->responseJson([
            'html' => $form,
        ]);
    }

    /**
     * @return array
     * @throws ModelValidateException
     */
    public function actionAddCustomer()
    {
        $attributes = $this->getParams();
        $clubId = (int) $this->getParam('clubId');

        $customerPlace = new CustomerPlace();
        $customerPlace->load($attributes);
        $customerPlace->place_id = $clubId;
        if ($customerPlace->users) {
            $customerPlace->user_id = reset($customerPlace->users);
        }
        $customerPlace->throwExceptionIfNotValid();

        $customerPlaceService = new CustomerPlaceService();
        $customerPlaceService->addCustomersToClub($clubId, $customerPlace->users);

        $clientsSearch = new CustomerPlaceSearch($clubId);

        $customersList = $this->renderAjax('/club/partial/customers-list', [
            'clientsDataProvider' => $clientsSearch->getSearchDataProvider(),
        ]);

        return $this->responseJson([
            'html' => $customersList,
        ]);
    }

    /**
     * @param $id
     * @return array
     * @throws \Throwable
     */
    public function actionUpdateCustomer($id)
    {
        $attributes = \Yii::$app->request->post();

        $customer = Customer::findOne($id);
        $userService = new UserService();
        $userService->updateCustomerByData($customer, $attributes);

        $customerPlace = new CustomerPlace();
        $customerPlace->load($attributes);
        $clientsSearch = new CustomerPlaceSearch((int) $customerPlace->place_id);

        $customersList = $this->renderAjax('/club/partial/customers-list', [
            'clientsDataProvider' => $clientsSearch->getSearchDataProvider(),
        ]);

        return $this->responseJson([
            'html' => $customersList,
        ]);
    }

    public function actionDeleteCustomer()
    {
        $clubId = (int) $this->getParam('clubId');
        $userId = (int) $this->getParam('userId');

        $customerPlaceService = new CustomerPlaceService();
        $customerPlaceService->rejectCustomerFromClub($userId, $clubId);

        $clientsSearch = new CustomerPlaceSearch($clubId);

        $customersList = $this->renderAjax('/club/partial/customers-list', [
            'clientsDataProvider' => $clientsSearch->getSearchDataProvider(),
        ]);

        return $this->responseJson([
            'html' => $customersList,
        ]);
    }

    /**
     * @return array
     * @throws ModelValidateException
     */
    public function actionSetStatus()
    {
        $clubId = (int) $this->getParam('clubId');
        $userId = (int) $this->getParam('userId');

        $customerPlaceService = new CustomerPlaceService();
        $customerPlaceService->toggleStatusByUserIdAndPlaceId($userId, $clubId);
        return $this->responseJson();
    }
}

views/club/partial/_translations.php
<?php

use app\src\entities\translate\Language;
use yii\helpers\Html;
use yii\jui\Accordion;
use app\src\widget\UFActiveForm;

/* @var Language[] $languages */

$items = [];
$form = UFActiveForm::begin(['id' => 'club-update-info-form', 'options' => ['class' => 'js-club-update-info-form']]);
foreach ($languages as $languageId => $languageName) {
    $translation = $model->translations[$languageId];

    $header = Html::tag('div', '', ['class' => 'pull-left flag flag-' . $languageId]) . '&nbsp; ' . $languageName;

    $content = $form->field($translation, '[' . $languageId . ']address')->label(\Yii::t('app', 'Address'))
        . $form->field($translation, '[' . $languageId . ']description')->label(\Yii::t('app', 'Description'))->textarea(['rows' => 4]);

    $items[] = [
        'header' => $header,
        'content' => $content,
    ];
}
?>
    <div class="box-body">
        <div class="row">
            <div class="col-lg-8">
                <div class="translation-accordion">
                    <?= Accordion::widget([
                        'items' => $items,
                        'clientOptions' => [
                            'heightStyle' => 'content',
                            'animate' => ['duration' => 300],
                            'collapsible' => count($languages) > 1,
                            'active' => false,
                        ],
                        'headerOptions' => ['tag' => 'div'],
                    ]); ?>
                </div>

                <div class="box-footer">
                    <?= Html::submitButton(\Yii::t('app', 'Update Info'), [
                        'class' => 'js-button-process-info btn btn-success float-right',
                        'data-url' => 'update-info',
                        'data-form-name' => '.js-club-update-info-form',
                        'data-message' => [
                            'success' => Yii::t('app', 'Club data was saved.'),
                            'error' => Yii::t('app', 'Club data was\'t save!'),
                            'errorLoadImages' => Yii::t('app', 'Club images was\'t save!'),
                        ]
                    ]) ?>
                </div>
            </div>
        </div>
    </div>
<?php UFActiveForm::end() ?>

views/club/partial/attribute_form.php
<?php

use app\src\entities\attribute\Attribute;
use app\src\widget\UFActiveForm;
use yii\web\View;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

/**
 * @var View $this
 * @var string $processButtonTitle
 * @var Attribute $attribute
 * @var array $names
 * @var array $types
 */
$processButtonTitle = $processButtonTitle ?? ($attribute->isNewRecord ?
        \Yii::t('app', 'Add Attribute') :
        \Yii::t('app', 'Update Attribute'));

$form = UFActiveForm::begin(['id' => 'attribute-club-form']) ?>

<?php
if (!$attribute->isNewRecord) {
    echo $form->field($attribute, 'id', ['template' => '{input}'])->hiddenInput()->label(false);
}
?>
    <div class="row">

        <div class="col-xs-3">
            <span class="float-left label-attribute-name"><label for="select-names"><?= Yii::t('app', 'Name') ?></label></span>
        </div>

        <div class="col-xs-9">

            <div class="row attribute-name-row">

                <div class="col-xs-9">
                    <?= $form->field($attribute, 'name', ['options' => ['class' => 'row js-select-names', 'id' => 'select-names'],
                        'template' => '<div class="col-xs-12">{input}{error}</div>'
                    ])->widget(Select2::class, [
                        'data' => ArrayHelper::map($names, 'name', 'name'),
                        'options' => [
                            'class' => 'js-select-names',
                            'multiple' => false,
                            'prompt' => \Yii::t('app', 'select name'),
                        ],
                        'pluginOptions' => [
                            'tags' => true,
                            'tokenSeparators' => [','],
                        ],
                    ])->label(false) ?>

                    <?= $form->field($attribute, 'name', ['template' => '<div class="col-xs-12">{input}{error}</div>'])
                        ->textInput(['class' => 'row js-create-attribute-input create-attribute-name-input hidden', 'disabled' => true])->label(false); ?>
                </div>

                <div class="col-xs-3">

                    <?= Html::button(
                        '+',
                        [
                            'class' => 'js-button-create-attribute-name create-attribute-name-btn btn btn-sm btn-success float-right',
                        ]
                    ) ?>
                </div>
            </div>
        </div>
    </div>

<?= $form->field($attribute, 'type')->widget(Select2::class, [
    'data' => $types,
    'options' => [
        'class' => 'js-type-select',
        'multiple' => false,
        'prompt' => \Yii::t('app', 'select type'),
    ],
    'pluginOptions' => [
        'tags' => true,
        'tokenSeparators' => [','],
    ],
])->label(\Yii::t('app', 'Type')) ?>

<?= $form->field($attribute, 'value', [
    'options' => [
        'tag' => 'div',
        'class' => 'row js-value-attribute-string hidden',
        'disabled' => true
    ],
    'template' => '<div class="col-xs-3"></div><div class="col-xs-9">{input}{error}</div>'
])->textInput([
    'type' => 'string'
])->label(false) ?>

<?= $form->field($attribute, 'value', [
    'options' => [
        'tag' => 'div',
        'class' => 'row js-value-attribute-number hidden',
        'disabled' => true
    ],
    'template' => '<div class="col-xs-3"></div><div class="col-xs-9">{input}{error}</div>'
])->textInput([
    'type' => 'number'
])->label(false) ?>

<?= $form->field($attribute, 'value', [
    'options' => [
        'tag' => 'div',
        'class' => 'row js-value-attribute-bool hidden',
        'disabled' => true,
    ]])->checkbox([
    'label' => 'enable',
    'class' => 'js-value-attribute-bool',
]); ?>

<?= Html::button(
    \Yii::t('app', $processButtonTitle),
    [
        'class' => 'js-button-process btn btn-success float-right',
        'autofocus' => 1,
    ]
) ?>

<?= Html::button(
    \Yii::t('app', 'Cancel'),
    [
        'class' => 'js-button-cancel btn btn-secondary float-right mr-3',
        'autofocus' => 1,
    ]
) ?>

<?php UFActiveForm::end() ?>

views/club/partial/attributes-list.php
<?php

use app\src\entities\attribute\Attribute;
use app\src\library\AccessChecker;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use app\src\widget\UFGridView;
use yii\helpers\Url;
use yii\web\View;

/**
 * @var View $this
 * @var ActiveDataProvider $attributesDataProvider
 */

$hasCreateAttributePermission = AccessChecker::hasPermission('attribute-club.change-clubs-attributes');
$hasDeleteAttributePermission = AccessChecker::hasPermission('attribute-club.delete-clubs-attributes');
?>

<div class="js-attributes-container uf-listing">
    <div class="box-body">
        <div class="nav-tabs-buttons">
            <?php if ($hasCreateAttributePermission) {
                echo Html::button(\Yii::t('app', 'Add Attribute'), [
                    'data-title' => \Yii::t('app', 'Add Attribute'),
                    'data-message' => [
                        'success' => Yii::t('app', 'Attribute have been successfully added.'),
                        'error' => Yii::t('app', 'Attribute have\'t been added.'),
                    ],
                    'class' => 'js-button-add-attribute btn btn-sm btn-warning',
                ]);
            } ?>
        </div>

        <?= UFGridView::widget([
            'dataProvider' => $attributesDataProvider,
            'columns' => [
                [
                    'attribute' => 'id',
                    'label' => Yii::t('app', 'ID'),
                ],
                [
                    'attribute' => 'name',
                    'label' => Yii::t('app', 'Name'),
                ],
                [
                    'attribute' => 'value',
                    'format' => 'raw',
                    'label' => Yii::t('app', 'Value'),
                    'value' => function ($model) {
                        if ((int) $model['type'] === Attribute::TYPE_BOOLEAN) {

                            $statusClasses = (bool) $model['value'] ?
                                'glyphicon-ok-circle text-success' : 'glyphicon-remove text-danger';
                            return Html::tag('span', '', [
                                'class' => 'glyphicon ' . $statusClasses,
                            ]);
                        } else {
                            return $model['value'];
                        }
                    }
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'buttons' => [
                        'delete' => function ($url, $model) use ($hasDeleteAttributePermission) {
                            if (!$hasDeleteAttributePermission) {
                                return '';
                            }
                            $title = htmlspecialchars(Yii::t('app', 'Delete attribute'));
                            $message = htmlspecialchars(Yii::t('app',
                                    'Do you really want to delete') . '"' . $model['name'] . '" ?');

                            return Html::tag('span', '', [
                                'class' => "js-delete-attribute uf-listing-button uf-listing-button-delete glyphicon glyphicon-trash",
                                'data-title' => $title,
                                'data-confirm-message' => $message,
                                'data-url' => $url,
                                'data-notification-message' => [
                                    'success' => Yii::t('app', 'Attribute have been successfully deleted.'),
                                    'error' => Yii::t('app', 'Attribute have\'t been deleted.'),
                                ],
                            ]);
                        },
                        'update' => function ($url, $model) use ($hasCreateAttributePermission) {
                            if (!$hasCreateAttributePermission) {
                                return '';
                            }
                            $title = Yii::t('app', 'Update ') . '"' . $model['name'] . '"' . Yii::t('app', ' attribute');
                            return Html::tag('span', '', [
                                'class' => "js-button-update-attribute uf-listing-button uf-listing-button-edit glyphicon glyphicon-pencil",
                                'data-title' => $title,
                                'data-url' => $url,
                                'data-message' => [
                                    'success' => Yii::t('app', 'Attribute have been successfully updated.'),
                                    'error' => Yii::t('app', 'Attribute have\'t been updated.'),
                                ],
                            ]);
                        },
                        'view' => function () {
                            return '';
                        }

                    ],
                    'urlCreator' => function ($action, $model) {
                        switch ($action) {
                            case 'update': return Url::to(['attribute-club/get-create-form', 'attributeId' => $model['id'], 'clubId' => $model['parent_id']]);
                            case 'delete': return Url::to(['attribute-club/delete', 'attributeId' => $model['id'], 'clubId' => $model['parent_id']]);
                            default: return '';
                        }
                    }
                ],
            ],
        ]); ?>
    </div>
</div>

views/club/partial/customers-list.php
<?php

use app\src\entities\customer\CustomerPlace;
use app\src\library\AccessChecker;
use yii\data\ActiveDataProvider;
use app\src\widget\UFGridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

/**
 * @var View $this
 * @var ActiveDataProvider $clientsDataProvider
 */

$hasSetStatusPermission = AccessChecker::hasPermission('customer-place.set-status');
$hasCreateAttributePermission = AccessChecker::hasPermission('customer-place.add-customers-form');
$hasDeleteCustomerPermission = AccessChecker::hasPermission('customer-place.delete-customer');
?>

<div class="js-customers-container uf-listing">
    <div class="box-body">
        <div class="nav-tabs-buttons">
            <?php if (AccessChecker::hasActionAccess('customer-place.add-customers-form')) {
                echo Html::button(\Yii::t('app', 'Add Customers'), [
                    'data-title' => \Yii::t('app', 'Add Customer'),
                    'data-message' => [
                        'success' => Yii::t('app', 'Customer have been successfully added.'),
                        'error' => Yii::t('app', 'Customer have\'t been added.'),
                    ],
                    'class' => 'js-button-add-customer btn btn-sm btn-warning',
                ]);
            } ?>

            <?php if (AccessChecker::hasPermission('customer.create')) {
                echo Html::button(\Yii::t('app', 'Create Customer'), [
                    'data-title' => \Yii::t('app', 'Create Customer'),
                    'data-message' => [
                        'success' => Yii::t('app', 'Customer have been successfully created.'),
                        'error' => Yii::t('app', 'Customer have\'t been created.'),
                    ],
                    'class' => 'js-button-create-customer btn btn-sm btn-warning']);
            } ?>
        </div>

        <?php \yii\widgets\Pjax::begin(['id' => 'club-cp']); ?>

        <?= UFGridView::widget([
            'dataProvider' => $clientsDataProvider,
            'columns' => [
                [
                    'attribute' => 'username',
                    'label' => Yii::t('app', 'Username'),
                ],
                [
                    'attribute' => 'fullname',
                    'label' => Yii::t('app', 'Fullname'),
                ],
                [
                    'attribute' => 'email',
                    'label' => Yii::t('app', 'Email'),
                ],
                [
                    'attribute' => 'card_number',
                    'label' => Yii::t('app', 'Card number'),
                ],
                [
                    'attribute' => 'phone',
                    'label' => Yii::t('app', 'Phone'),
                ],
                [
                    'label' => Yii::t('app', 'Date of Birthday'),
                    'attribute' => 'birthday',
                    'value' => 'birthday',
                ],
                [
                    'attribute' => 'description',
                    'label' => Yii::t('app', 'Description'),
                ],
                [
                    'label' => Yii::t('app', 'Status'),
                    'format' => 'raw',
                    'contentOptions' => ['class' => 'text-center'],
                    'value' => function ($model) use ($hasSetStatusPermission) {
                        $statusClasses = (int) $model['status'] === CustomerPlace::STATUS_PENDING ?
                            'label-danger' : 'label-success';
                        $statusLabel = (int) $model['status'] === CustomerPlace::STATUS_PENDING ?
                            Yii::t('app', 'Pending') : Yii::t('app', 'Approved');
                        $jsClass = $hasSetStatusPermission ? 'js-set-status' : '';
                        return Html::tag('span', $statusLabel, [
                            'class' => $jsClass . ' uf-customer-change-status label ' . $statusClasses,
                            'data-url' => Url::to([
                                'customer-place/set-status', 'userId' => $model['user_id'], 'clubId' => $model['club_id']
                            ]),
                            'data-message' => [
                                'success' => Yii::t('app', 'Customers status have been successfully updated.'),
                                'error' => Yii::t('app', 'Customers status have\'t been updated.'),
                            ],
                            'data-labels' => [
                                'success' => Yii::t('app', 'Approved'),
                                'warning' => Yii::t('app', 'Pending'),
                            ],
                        ]);
                    }

                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'buttons' => [
                        'delete' => function ($url, $model) use ($hasDeleteCustomerPermission) {
                            if (!$hasDeleteCustomerPermission) {
                                return '';
                            }
                            $title = htmlspecialchars(Yii::t('app', 'Delete customer from club'));
                            $message = htmlspecialchars(Yii::t('app',
                                    'Do you really want to delete ') . '"' . $model['username'] . '" ?');

                            return Html::tag('span', '', [
                                'class' => "js-button-delete-customer uf-listing-button uf-listing-button-edit glyphicon glyphicon-trash",
                                'data-title' => $title,
                                'data-confirm-message' => $message,
                                'data-url' => $url,
                                'data-notification-message' => [
                                    'success' => Yii::t('app', 'Customer have been successfully deleted.'),
                                    'error' => Yii::t('app', 'Customer have\'t been deleted.'),
                                ],
                            ]);
                        },
                       'update' => function ($url, $model) use ($hasCreateAttributePermission) {
                            if (!$hasCreateAttributePermission) {
                                return '';
                            }
                           $title = Yii::t('app', 'Update ') . '"' . $model['username'] . '"' . Yii::t('app', ' customer');
                           return Html::tag('span', '', [
                               'class' => "js-button-update-customer uf-listing-button uf-listing-button-edit glyphicon glyphicon-pencil",
                               'data-title' => $title,
                               'data-url' => $url,
                               'data-customer-id' => $model['user_id'],
                               'data-message' => [
                                   'success' => Yii::t('app', 'Customer have been successfully updated.'),
                                   'error' => Yii::t('app', 'Customer have\'t been updated.'),
                               ],
                           ]);
                       },
                        'view' => function () {
                            return '';
                        }

                    ],
                    'urlCreator' => function ($action, $model) {
                        switch ($action) {
                            case 'update': return Url::to(['customer-place/get-update-form',
                                'customer_id' => $model['user_id'],
                                'club_id' => $model['club_id']
                            ]);
                            case 'delete': return Url::to([
                                    'customer-place/delete-customer',
                                    'clubId' => $model['club_id'],
                                    'userId' => $model['user_id']
                                ]);
                            default: return '';
                        }
                    }
                ],
            ],
        ]); ?>

        <?php \yii\widgets\Pjax::end(); ?>

    </div>
</div>