controllers/ActivityController.php
<?php
namespace app\controllers;

use app\src\entities\AbstractModel;
use app\src\entities\activity\Activity;
use app\src\entities\activity\ActivitySearch;
use app\src\entities\place\Club;
use app\src\entities\staff\StaffSearch;
use app\src\library\AccessChecker;
use app\src\library\BaseController;
use app\src\service\ActivityService;

/**
 * Class ActivityController
 */
class ActivityController extends BaseController
{
    /**
     * Lists all Activity models.
     */
    public function actionIndex()
    {
        $activity = new ActivitySearch();
        $params = \Yii::$app->request->queryParams;
        $dataProvider = $activity->getSearchDataProvider($params);

        $this->appendEntryPoint('listing');

        return $this->render('index', [
            'searchModel' => $activity,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView()
    {
        $activityId = (int) $this->getParam('id');

        $activity = Activity::findOne($activityId);

        $this->appendEntryPoint('view');

        return $this->render('view', [
            'activity' => $activity,
            'organizers' => $activity->organizers
        ]);
    }

    public function actionCreate()
    {
        $attributes = $this->getParams();

        if (\Yii::$app->request->isPost) {
            $activityService = new ActivityService();
            $activityService->createActivityByData($attributes);
            return $this->redirect('/activity/index');
        }

        $clubs = AccessChecker::isSuperAdmin() ?
            Club::getAll() :
            Club::getClubsByUserId(\Yii::$app->user->getId());

        $staffSearch = new StaffSearch();
        $organizers = $staffSearch->getSearchQuery()->all();

        return $this->render('create', [
            'activity' => new Activity(),
            'clubs' => $clubs,
            'organizers' => $organizers
        ]);
    }

    public function actionDelete()
    {
        $activityId = (int) $this->getParam('id');

        $activityService = new ActivityService();
        $activityService->deleteById($activityId);

        return $this->responseListing(new ActivitySearch(), '/activity/index');
    }

    public function actionUpdate($id)
    {
        $attributes = \Yii::$app->request->post();
        $activityService = new ActivityService();

        if ($attributes) {
            $activityService->updateActivityByData((int) $id, $attributes);
            return $this->redirect('/activity/index');
        }

        $clubs = AccessChecker::isSuperAdmin() ?
            Club::getAll() :
            Club::getClubsByUserId(\Yii::$app->user->getId());

        $activity = Activity::findOne($id);

        $this->appendEntryPoint('input-file');

        return $this->render('create', [
            'activity' => $activity,
            'clubs' => $clubs,
            'organizers' => $activity->organizers
        ]);
    }

    /**
     * @param $id
     * @param $filename
     * @param $extPath
     * @param AbstractModel|null $model
     * @return array
     */
    public function actionDeleteImage($id, $filename, $extPath, AbstractModel $model = null)
    {
        return parent::actionDeleteImage($id, $filename, $extPath, new Activity());
    }
}

controllers/ClubController.php
<?php
namespace app\controllers;

use app\src\entities\AbstractModel;
use app\src\entities\attribute\AttributeClubSearch;
use app\src\entities\customer\CustomerPlaceSearch;
use app\src\entities\image\Image;
use app\src\entities\place\Club;
use app\src\entities\place\ClubSearch;
use app\src\entities\staff\StaffPositionPlaceSearch;
use app\src\entities\user\User;
use app\src\library\AccessChecker;
use app\src\library\BaseController;
use app\src\service\ClubService;
use app\src\service\ImageService;
use app\src\service\PlaceService;

/**
 * Class ClubController
 */
class ClubController extends BaseController
{
    /**
     * Lists all Club models.
     */
    public function actionIndex()
    {
        $place = new ClubSearch();
        $params = \Yii::$app->request->queryParams;
        $dataProvider = $place->getSearchDataProvider($params);

        $this->appendEntryPoint();

        return $this->render('index', [
            'searchModel' => $place,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate()
    {
        $attributes = $this->getParams();

        $clubService = new ClubService();
        $club = $clubService->createEmptyClub($attributes);

        $redirectUrl = '/club/update?id=' . $club->id;
        if (!AccessChecker::hasPermission('club.update')) {
            $redirectUrl = '/club/index';
        }

        return $this->responseJson([
            'redirectUrl' => $redirectUrl,
        ]);
    }

    public function actionGetCreateClubForm()
    {
        $form = $this->renderAjax('/club/partial/create-club-form', [
            'club' => new Club(),
        ]);

        return $this->responseJson([
            'html' => $form,
        ]);
    }

    public function actionDelete()
    {
        $clubId = $this->getParam('id');
        $isAjax = $this->getParam('isAjax');

        $clubService = new PlaceService();
        $clubService->deleteById($clubId);

        if ($isAjax) {
            return $this->responseListing(new ClubSearch(), '/club/index');
        }

        return $this->redirect('/club/index');
    }

    public function actionUpdate($id)
    {
        $owners = User::getOwnerList();
        $club = Club::findOne($id);
        $params = $this->getParams();

        $staffPositionPlaceSearch = new StaffPositionPlaceSearch($club->id);
        $customerPlaceSearch = new CustomerPlaceSearch($club->id);
        $attributePlaceSearch = new AttributeClubSearch($club->id);

        $this->appendEntryPoint();

        return $this->render('create', [
            'club' => $club,
            'owners' => $owners,
            'staffPositionPlaceSearch' => $staffPositionPlaceSearch,
            'staffDataProvider' => $staffPositionPlaceSearch->getSearchDataProvider($params),
            'clientsDataProvider' => $customerPlaceSearch->getSearchDataProvider(),
            'attributesDataProvider' => $attributePlaceSearch->getSearchDataProvider(),
        ]);
    }

    /**
     * @param $id
     * @throws \app\src\exception\ModelValidateException
     */
    public function actionUpdateInfo($id)
    {
        $attributes = \Yii::$app->request->post();

        $club = Club::findOne($id);
        $club->load($attributes);
        $club->updated_at = $club->updated_at ?? AbstractModel::getDateTimeNow();
        $club->updated_by = $club->updated_by ?? \Yii::$app->user->getId();
        $club->throwExceptionIfNotValid();
        $club->save();
        $this->appendEntryPoint('club.update');
    }

    public function actionUploadImages($id)
    {
        $club = Club::findOne($id);

        $imageService = new ImageService();
        $imageService->uploadImages($club, $_FILES, Image::TYPE_PLACE_PHOTO);
        $imageService->uploadLogo($club, $_FILES, Image::TYPE_PLACE_LOGO);
    }

    /**
     * @param $id
     * @param $filename
     * @param $extPath
     * @param AbstractModel $modelClass
     * @return array
     */
    public function actionDeleteImage($id, $filename, $extPath, AbstractModel $modelClass = null)
    {
        return parent::actionDeleteImage($id, $filename, $extPath, new Club());
    }
}

views/club/create.php
<?php

use app\src\entities\place\Club;
use app\src\entities\user\User;
use app\src\entities\translate\Language;
use yii\web\View;

/* @var View $this */
/* @var Club $club */
/* @var User[] $owners */

$this->title = \Yii::t('app', 'Club Update');
$this->params['breadcrumbs'][] = ['label' => \Yii::t('app', 'Clubs'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="nav-tabs-form js-nav-tabs">
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#club-update-info" data-toggle="tab" aria-expanded="false"><?= \Yii::t('app', 'Info') ?></a>
        </li>
        <li>
            <a href="#club-update-contacts" data-toggle="tab"
               aria-expanded="false"><?= \Yii::t('app', 'Contacts') ?></a>
        </li>
        <li>
            <a href="#staff" data-toggle="tab" aria-expanded="false"><?= \Yii::t('app', 'Staff') ?></a>
        </li>
        <li>
            <a href="#attributes" data-toggle="tab" aria-expanded="false"><?= \Yii::t('app', 'Attributes') ?></a>
        </li>
        <li>
            <a href="#customers" data-toggle="tab" aria-expanded="false"><?= \Yii::t('app', 'Customers') ?></a>
        </li>
        <li>
            <a href="#payment" data-toggle="tab" aria-expanded="false"><?= \Yii::t('app', 'Payment') ?></a>
        </li>
        <li>
            <a href="#translations" data-toggle="tab" aria-expanded="false"><?= \Yii::t('app', 'Translations') ?></a>
        </li>
    </ul>

    <div class="tab-content js-edit-club-container" data-club_id="<?= $club->id ?>">
<!--        <div class="container-fluid">-->
            <div class="tab-pane active" id="club-update-info">
                <?= $this->render('/club/partial/main-form.php', $_params_) ?>
            </div>
<!--        </div>-->
        <div class="tab-pane" id="club-update-contacts">
            <?= $this->render('/club/partial/contacts-form.php', $_params_) ?>
        </div>
        <div class="tab-pane" id="staff">
            <?= $this->render('/club/partial/staff-list.php', $_params_ + ['clubId' => $club->id]) ?>
        </div>
        <div class="tab-pane" id="attributes">
            <?= $this->render('/club/partial/attributes-list.php', $_params_) ?>
        </div>
        <div class="tab-pane" id="customers">
            <?= $this->render('/club/partial/customers-list.php', $_params_) ?>
        </div>
        <div class="tab-pane" id="payment">
            <?= $this->render('/club/partial/payment.php', $_params_) ?>
        </div>
        <div class="tab-pane" id="translations">
            <?= $this->render('/club/partial/_translations', [
                'model' => $club,
                'languages' => Language::getList(),
            ]) ?>
        </div>
    </div>
    <?= $this->render('/_templates/confirm-dialog.php') ?>
</div>

views/club/index.php
<?php

use app\src\entities\place\Club;
use app\src\entities\place\ClubSearch;
use app\src\helpers\ImageHelper;
use app\src\helpers\ViewHelper;
use app\src\library\AccessChecker;
use kartik\datecontrol\DateControl;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use app\src\widget\UFGridView;
use yii\helpers\Url;
use yii\web\View;

/* @var View $this */
/* @var ClubSearch $searchModel */
/* @var ActiveDataProvider $dataProvider */

$this->title = Yii::t('app', 'Clubs');
$this->params['breadcrumbs'][] = $this->title;

$hasUpdateClubPermission = AccessChecker::hasPermission('club.update');
$hasDeleteClubPermission = AccessChecker::hasPermission('club.delete');

echo ViewHelper::getJSMap(ViewHelper::JS_MAP_TRANSLATE, [
    'delete_popup.confirm_title' => Yii::t('app', 'Do you really want to delete this club?'),
]);
?>

<div class="box uf-listing js-listing">

    <div class="box-header">
        <h3 class="box-title"><?= Yii::t('app', 'Club List') ?></h3>

        <?php if (AccessChecker::hasPermission('club.create')) {
            echo Html::button(Yii::t('app', 'Create Club'), [
                'data-url' => Url::to(['club/get-create-club-form']),
                'data-title' => \Yii::t('app', 'Club Create'),
                'data-notification-message' => [
                    'success' => Yii::t('app', 'Club have been successfully created.'),
                    'error' => Yii::t('app', 'Club have\'t been created.'),
                ],
                'class' => 'js-button-create btn btn-sm btn-success float-right',
            ]);
        } ?>

    </div>

    <div class="box-body">

        <?php \yii\widgets\Pjax::begin(['id' => 'club-index']); ?>

        <?= $this->render('/_templates/confirm-dialog.php') ?>
        <div class="club-index">
            <?= UFGridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    'id',
                    [
                        'attribute' => 'name',
                        'sortLinkOptions' => ['class' => 'sorting'],
                    ],
                    [
                        'attribute' => 'city',
                        'sortLinkOptions' => ['class' => 'sorting'],
                    ],
                    'address',
                    [
                        'attribute' => 'logo',
                        'format' => 'raw',
                        'value' => function ($model) {
                            if (empty($model['logo'])) {
                                return null;
                            }
                            $html = '';
                            $place = new Club(['id' => $model['id']]);
                            $html = $html . '<img class="img-thumbnail" src="' . ImageHelper::getUrl($place, $model['logo'], '/logo') . '"></img>';
                            return Html::a($html);
                        }
                    ],
                    'description',
                    [
                        'attribute' => 'created_at',
                        'filter' => DateControl::widget([
                            'model' => $searchModel,
                            'type' => DateControl::FORMAT_DATE,
                            'attribute' => 'created_at',
                            'widgetOptions' => [
                                'pluginOptions' => [
                                    'format' => 'php:Y-m-d'
                                ]
                            ],
                            'autoWidget' => true,
                        ]),
                        'headerOptions' => ['style' => 'min-width: 220px'],
                        'format' => 'html',
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'buttons' => [
                            'view' => function ($url, $model) {
                                return '';
                            },
                            'update' => function ($url, $model) use ($hasUpdateClubPermission) {
                                if (!$hasUpdateClubPermission) {
                                    return '';
                                }
                                $title = htmlspecialchars(Yii::t('app', 'Update "') . $model['name'] . '"');
                                return Html::a('<span class="glyphicon glyphicon-pencil"
                                    data-title="' . $title . '"></span>', $url);
                            },
                            'delete' => function ($url, $model) use ($hasDeleteClubPermission) {
                                if (!$hasDeleteClubPermission) {
                                    return '';
                                }

                                $title = htmlspecialchars(Yii::t('app', 'Club Delete'));
                                $message = htmlspecialchars(Yii::t('app', 'Do you really want to delete "') . $model['name'] . Yii::t('app', '" club') . '?');
                                return Html::tag('span', '', [
                                    'class' => 'js-delete uf-listing-button uf-listing-button-delete glyphicon glyphicon-trash',
                                    'data-url' => $url,
                                    'data-title' => $title,
                                    'data-confirm-message' => $message,
                                    'data-notification-message' => [
                                        'success' => Yii::t('app', 'Club have been successfully deleted.'),
                                        'error' => Yii::t('app', 'Club have\'t been deleted.'),
                                    ],
                                ]);
                            },
                        ],
                        'urlCreator' => function ($action, $model) {
                            switch ($action) {
                                case 'update': return Url::to(['club/update', 'id' => $model['id']]);
                                case 'delete': return Url::to(['club/delete', 'id' => $model['id']]);
                                default: return Url::to(['club/view', 'id' => $model['id']]);
                            }
                        }
                    ],
                ],
            ]); ?>
        </div>
        <?php \yii\widgets\Pjax::end(); ?>

        <script>
            window.fbAsyncInit = function () {
                FB.init({
                    //appId      : '133432240860324',
                    appId: '277210412864977',
                    xfbml: true,
                    version: 'v3.0'
                });
                FB.AppEvents.logPageView();
            };

            (function (d, s, id) {
                return;
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) {
                    return;
                }
                js = d.createElement(s);
                js.id = id;
                js.src = "https://connect.facebook.net/en_US/sdk.js";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));

            function fbLogin() {
                FB.getLoginStatus(function (response) {
                    if (response.authResponse) {
                        console.log('Welcome!  Fetching your information.... ');
                        console.log(response);
                    } else {
                        console.log('Юзер был не залогинен в самом ФБ, запускаем окно логинизирования');
                        FB.login(function (response) {
                            if (response.authResponse) {
                                console.log('Welcome!  Fetching your information.... ');
                                console.log(response);
                            } else {
                                console.log('Походу пользователь передумал логиниться через ФБ');
                            }
                        });
                    }
                }, {
                    scope: 'email,id'
                });
            }
        </script>

        <button style="display: none" onclick="fbLogin()">LOGIN FACEBOOK</button>

    </div>
</div>